-- ERD 정보 확인용 쿼리들

-- 1. 모든 테이블 목록
SELECT TABLE_NAME, TABLE_TYPE 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'PUBLIC'
ORDER BY TABLE_NAME;

-- 2. 테이블별 컬럼 정보
SELECT 
    t.TABLE_NAME,
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.CHARACTER_MAXIMUM_LENGTH,
    c.IS_NULLABLE,
    c.COLUMN_DEFAULT,
    CASE WHEN pk.COLUMN_NAME IS NOT NULL THEN 'PK' ELSE '' END as IS_PRIMARY_KEY
FROM INFORMATION_SCHEMA.TABLES t
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE pk ON c.TABLE_NAME = pk.TABLE_NAME AND c.COLUMN_NAME = pk.COLUMN_NAME
WHERE t.TABLE_SCHEMA = 'PUBLIC' AND t.TABLE_TYPE = 'TABLE'
ORDER BY t.TABLE_NAME, c.ORDINAL_POSITION;

-- 3. 외래키 관계 정보
SELECT 
    rc.CONSTRAINT_NAME,
    kcu1.TABLE_NAME AS FK_TABLE,
    kcu1.COLUMN_NAME AS FK_COLUMN,
    kcu2.TABLE_NAME AS REFERENCED_TABLE,
    kcu2.COLUMN_NAME AS REFERENCED_COLUMN
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu1 ON rc.CONSTRAINT_NAME = kcu1.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu2 ON rc.UNIQUE_CONSTRAINT_NAME = kcu2.CONSTRAINT_NAME
ORDER BY rc.CONSTRAINT_NAME;

-- 4. 인덱스 정보
SELECT 
    INDEX_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    NON_UNIQUE
FROM INFORMATION_SCHEMA.INDEXES
WHERE TABLE_SCHEMA = 'PUBLIC'
ORDER BY TABLE_NAME, INDEX_NAME;